apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-with-payload-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  repeat: true
  imageVersion: "latest"
  serviceAccountName: argo-events
  signals:
    - name: webhook-gateway/webhook.payloadConfig
  triggers:
    - name: webhook-payload-trigger
      resource:
        namespace: argo
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        parameters:
          - src:
              signal: webhook-gateway/webhook.payloadConfig
            # pass payload of webhook-gateway/webhook.fooConfig signal to first parameter value
            # of arguments.
            dest: spec.arguments.parameters.0.value
        source:
          inline: |
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-payload-
                # name: arguments-via-webhook-event
              spec:
                entrypoint: whalesay
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
                arguments:
                  parameters:
                  - name: message
                    # this is the value that should be overridden
                    value: hello world
