apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    singular: gateway
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sensors.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Sensor
    listKind: SensorList
    plural: sensors
    singular: sensor
  scope: Namespaced
  version: v1alpha1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-events-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-events-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-events-sa
  namespace: argo-events
---
apiVersion: v1
data:
  config: |
    instanceID: argo-events
    namespace: argo-events
kind: ConfigMap
metadata:
  name: gateway-controller-configmap
---
apiVersion: v1
data:
  config: |
    instanceID: argo-events
    namespace: argo-events
kind: ConfigMap
metadata:
  name: sensor-controller-configmap
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-controller
    spec:
      containers:
      - env:
        - name: GATEWAY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GATEWAY_CONTROLLER_CONFIG_MAP
          value: gateway-controller-configmap
        image: argoproj/gateway-controller:latest
        imagePullPolicy: Always
        name: gateway-controller
      serviceAccountName: argo-events-sa
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sensor-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sensor-controller
    spec:
      containers:
      - env:
        - name: SENSOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SENSOR_CONFIG_MAP
          value: sensor-controller-configmap
        image: argoproj/sensor-controller:latest
        imagePullPolicy: Always
        name: sensor-controller
      serviceAccountName: argo-events-sa
